### ISSUE TITLE
Small howtow

### ISSUE THREAD

**Issue by frekel** [pkozul/ha-floorplan#1]
Can you please write a small installation howto?

Thanks,
Frank

**Comment by dobrynski** [comment]
+1

There is no information on how to use this at all.

**Comment by frekel** [comment]
Maybe we can figure something out from his older version:  https://github.com/pkozul/ha-floorplan-state-card?

**Comment by dobrynski** [comment]
Well that would be my strategy, but then why abandon the old one in favour of this one and not propagate the documentation forward?

**Comment by pkozul** [comment]
Documentation completed.

**Comment by frekel** [comment]
GREAT! Thanks!

**Comment by dobrynski** [comment]
Thank you very much!
