### ISSUE TITLE
Floorplan without sidebar and toolbar

### ISSUE THREAD

**Issue by aureliosaraiva** [pkozul/ha-floorplan#104]
Is it possible to open the floorplan without HomeAssistant's sidebar and toolbar? I would like to open only it.

**Comment by Pablohn26** [comment]
Do you mean this PR https://github.com/pkozul/ha-floorplan/pull/86?

**Comment by pkozul** [comment]
Floorplan has been revamped.. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
