### ISSUE TITLE
Floorplan shows OFF on HA frontend

### ISSUE THREAD

**Issue by HFeenstra** [pkozul/ha-floorplan#23]
I followed your steps so far and do get an OFF statement on the Floorplan 
![image](https://user-images.githubusercontent.com/25987376/28499920-7dfcb9bc-6fc0-11e7-84d2-77002e006216.png)
What have I done wrong, what did I missed?

Furthermore: in the configuration file of HA I have this:
customize: !include_dir_merge_named customizations
             !include customize.yaml

Is this correct? Will this work?

**Comment by pkozul** [comment]
Looks like your customization is not being picked by HA.

Is this what you have?

**configuration.yaml**
```
homeassistant:
  customize: !include customize.yaml
```

**customize.yaml**

```
    binary_sensor.floorplan:
      custom_ui_state_card: floorplan
      config: !include floorplan.yaml
```

Does your HA log file report anything?

**Comment by HFeenstra** [comment]
Hi Peter,

Thanks for getting back to me! So I had 2 lines of code in my configuration.yaml file. Comment the one that shouldn't be working any more and then it came up  not as off or on. 
But in stead it now keeps on spinning in the card it self, as if it needs to read a file...
![image](https://user-images.githubusercontent.com/25987376/28584332-a7906be0-716c-11e7-8555-6959f7654c93.png)

Oh and no the info file doesn't show anything about the floorplan

**Comment by pkozul** [comment]
Using Google Chrome, press F12 to show the Developer Tools. Refresh the page by pressing F5. Do any errors get displayed in the Console window?

**Comment by HFeenstra** [comment]
Hi,

I see this:

ha-floorplan.html:857 Uncaught ReferenceError: $ is not defined
    at HTMLElement.error (ha-floorplan.html:857)
    at HTMLElement.handleWindowError (ha-floorplan.html:173)


ha-floorplan.html:144 Uncaught ReferenceError: moment is not defined at
WebSocket.hass.connection.socket.addEventListener.event (
ha-floorplan.html:144)



2017-07-30 23:13 GMT+02:00 Petar Kozul <notifications@github.com>:

**Comment by schmic** [comment]
@HFeenstra Did you copy the lib-folder as well or just the two .html-files? Cause it seems that folder is missing.

**Comment by pkozul** [comment]
Sounds the like copying the lib folder was the missing step. Did that work out in the end?

**Comment by Phoenxi131178** [comment]
hey i got the Version 0.68 and have the same Problem. Now all is included but i can´t see the floorplan ...
It shows on the first Page only Floorplan off.
I used HA on a synology Nas maybe it doesn´t work :(

I got it. I used the Firefox !! 

on Google Chrome it is running.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
