### ISSUE TITLE
Move the tutorial to the wiki

### ISSUE THREAD

**Issue by vibrog** [pkozul/ha-floorplan#24]
Make the repository more suitable for installation and updating, with less overhead.

**Comment by shayshtern** [comment]
agree

**Comment by Landrash** [comment]
It's better to have documentation included in a place where it can't be edited by any one and reviews of the documentation can be handeld easier. Moving it to the wiki seems like a horrible idea since parts still will need to be hosted in the repository.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
