### ISSUE TITLE
Safari script error in HA 0.51.1

### ISSUE THREAD

**Issue by sjee105** [pkozul/ha-floorplan#28]
After updating HA to version 0.51.1 floorplan gives a script error in Safari on both mac and ipad. Chrome on the mac works but chrome on ipad doesn't. This might be related to latest changes in the frontend and polymer 2?

**Comment by andrewjfreyer** [comment]
Same issue

**Comment by snjoetw** [comment]
same here :(

**Comment by Amir974** [comment]
51.2 still does not load floorplan on iOS devices for me, any idea what's blocking it ?

**Comment by hliang0813** [comment]
same issue here :(
with HA 0.52.0

**Comment by benjaminreede** [comment]
The problem is due to Polymer 2.0 changes in HA 0.51 the external stylesheet can't be loaded. Haven't find a fix yet

**Comment by Amir974** [comment]
I still see same behavior in 0.52.1
is there a fix in the horizon ? workaround ?

**Comment by TheCellMC** [comment]
I did some troubleshooting but I can't seem to be able to find a fix. All I know is that it is cause by some Polymer 2.0 changes.

**Comment by mrfoxbit** [comment]
Same issue in HA 0.52.1

**Comment by ksheumaker** [comment]
Issue still exists in 0.53

**Comment by mrfoxbit** [comment]
- Issue still exists in 0.530.
- HA 0.53.0 still does not load floorplan on iOS devices. Home Assistant App iOS, safari (iphone, ipad , mac), chrome (iphone, ipad).
- Android devices work fine.
- Custom state card does not load floorplan (0.52.1 works fine)

**Comment by carlchan** [comment]
I suspect this won't be fixed until Polymer updates their browser support.  Need the "Polyfill" feature.
See here: https://www.polymer-project.org/2.0/docs/browsers

**Comment by namadori** [comment]
Time passes but still no glimpse of a resolution or even a workaround? 
I love floorplan, but at home we have 3 iPhones and 1 iPad so it's pretty useless.

**Comment by andrewjfreyer** [comment]
@namadori only solution at present is to roll back home assistant to version 0.49

**Comment by ghost** [comment]
any updates on this? Sucks i have 3 ipads mounted in the wall just for floorplan and cant use any of them =(

**Comment by kennhardy** [comment]
Same here..

**Comment by sjee105** [comment]
Problem is solved in version 1.06, thanks!

**Comment by danielpalstra** [comment]
Maybe a stupid question, but version 1.06 of what?

**Comment by sjee105** [comment]
Version 1.06 of floorplan

https://community.home-assistant.io/t/floorplan-for-home-assistant/17394/881

**Comment by danielpalstra** [comment]
I checked the releases of floorplan, but forgot to check the forum, thx :)

2017-10-17 15:05 GMT+02:00 sjee105 <notifications@github.com>:
