### ISSUE TITLE
hass.callService called multiple times

### ISSUE THREAD

**Issue by 0xphilipp** [pkozul/ha-floorplan#29]
Hi,

![image](https://user-images.githubusercontent.com/9350951/29290649-2ce1dffc-8141-11e7-8ef8-3c349a6b6a49.png)

When I add a console.log to onEntityClick, right before callService, it is being logged twice.

![image](https://user-images.githubusercontent.com/9350951/29290748-8523202c-8141-11e7-80b9-c3de83f7747b.png)

I think the click event should not be added for every child element, but only on the main element

```
$(svgElement).on('click', this.instance.onEntityClick.bind({ instance: this.instance, entityId: entityId }));

for (svgElementId in entityConfig.svgElementConfigs) {
```

This also fixed a flickering I had with my philips hue bulbs because it spammed the hue hub due to multiple calls.

**Comment by ryanrdetzel** [comment]
#43 Same. This solution is probably better but I feel there is something else that needs to be addressed in regards to the looping over groups.

**Comment by ebudalen** [comment]
can you please share this part of your html file (a bit text above and below your added lines) so I can see what you have deleted, and where excactly you have pasted it?

**Comment by romquenin** [comment]
Can you please share the workaround processus to solve this issue ?
Thank you very much.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
