### ISSUE TITLE
more than on floorplan?

### ISSUE THREAD

**Issue by mvillarejo** [pkozul/ha-floorplan#3]
Hello,

does someone has an example of how to have more than one floorplan? I've been trying to set that up but... no luck.

thanks

**Comment by CCOSTAN** [comment]
You might have to search and replace all instances of floorplan.html, floorplan.svg, floorplan.css with floorplan2.html, floorplan2.svg and floorplan2.css.

I haven't tried it yet but that's where I would start.

**Comment by pkozul** [comment]
Hi there,

I just posted some info on the HA forums, describing how to get multiple floorplans showing. Have a look there. Soon I will add it the readme in this repo.

Cheers.

**Comment by mvillarejo** [comment]
great news! any chance you can share the link to it?

**Comment by pkozul** [comment]
Sure. Here it is: https://community.home-assistant.io/t/floorplan-for-home-assistant/17394/303

**Comment by mvillarejo** [comment]
great news, I managed to make it work! thanks guys.

one last question, it seems that this dom-module id is causing errors:
`<dom-module id="ha-panel-p1">`
`Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at Object.jQuery.ajax.success.result.bind.instance (ha-floorplan.html:159)`

I'm not good with Polymer or javascript so... any idea why? 

cheers!

**Comment by mvillarejo** [comment]
This looks great, not sure what's wrong with that id but... it's not the end of the world to replace it with a non alphanumeric name.

suggestion now to close this issue.

Great job to the creators of this module, It'll be great if it becomes part of HA but obviously with your support! 

Cheers
