### ISSUE TITLE
White bar appears at bottom of page if tool bar disabled

### ISSUE THREAD

**Issue by mrardon** [pkozul/ha-floorplan#31]
Height is hardcoded and if app toolbar is hidden then whitespace appears at bottom of page.

https://github.com/pkozul/ha-floorplan/blob/master/panels/floorplan.html#L8

Not sure exact way to fix it for both show toolbar and hide toolbar (otherwise would have made a PR) but just setting to 100% solved my issue (full screen no app bar).

<img width="1387" alt="screen shot 2017-08-24 at 5 08 19 pm" src="https://user-images.githubusercontent.com/634533/29688788-e1dda9cc-88ee-11e7-9d3d-8d9943e61ff0.png">

**Comment by RyanRayNeff** [comment]
@mrardon I'm having the same issue. What setting did you set to 100% to fix this?

**Comment by mrardon** [comment]
@RyanRayNeff I linked the file and the line number above. However, It looks like 10 hours ago it was changed and may be fixed, I haven't used it in a while TBH.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
