### ISSUE TITLE
script not found 404

### ISSUE THREAD

**Issue by bymem** [pkozul/ha-floorplan#32]
hi im getting a :

webcomponents-lite.js.map
Failed to load resource: the server responded with a status of 404 (Not Found)

but i don't see the file any where in the git.

**Comment by kennhardy** [comment]
I do also have this issue.

**Comment by kennhardy** [comment]
Never mind. This problem is not related to ha-floorplan. The error message comes from home assistant itself and are present all over the web-gui. At least on my side.
