### ISSUE TITLE
Floorplan ui not clickable

### ISSUE THREAD

**Issue by sendorm** [pkozul/ha-floorplan#34]
Hello,

Since hass 0.50.x, floorplan items are not clickable. I tried on both ios 10.2 and ios 11 as well as kindle fire os 5.4.
Everything works on desktop pc.

**Comment by sendorm** [comment]
I was able to fix the unclickable aspect by disabling the `pan_zoom:`. So the problem becomes:

> ui is not clickable when pan_zoom is enabled

.

**Comment by jn84** [comment]
For anyone coming here in the future: https://github.com/pkozul/ha-floorplan/pull/59
