### ISSUE TITLE
Ability to add camera image to the Floorplan homepage

### ISSUE THREAD

**Issue by CCOSTAN** [pkozul/ha-floorplan#36]
I tried to use the image_template but it seems that is expecting an SVG.  It would be great to have maybe a camera_template that could use entitiy.attributes.entity_picture to display the current thumbnail image like in HASS.   

![image](https://user-images.githubusercontent.com/2160436/32117584-f2fb9fec-bb1c-11e7-9f79-936da1e6ee2c.png)

**Comment by CCOSTAN** [comment]
I just KNOW the answer is here : https://github.com/pkozul/ha-floorplan/blob/master/www/custom_ui/floorplan/ha-floorplan.html#L448-L459 - I'm just not smart enough to figure it out. :)

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
