### ISSUE TITLE
Multiple Binds

### ISSUE THREAD

**Issue by ryanrdetzel** [pkozul/ha-floorplan#43]
I have a problem that switches would turn off and then right back on. I tracked it down to the click event was being assigned multiple times because my switches are groups of object and each object was getting a click bind.

I'm not sure why each item needs to go through this loop but I fixed my issue with a simple condition to check if the bind has already happened. You might have a better solution though since you understand the code better.

`            var alreadyBound = false;
              for (svgElementId in entityConfig.svgElementConfigs) {
                let svgElementConfig = entityConfig.svgElementConfigs[svgElementId];

                let svgElement = $(svgElementConfig.svgElement);

                // Create a title element (to support hover over text)
                svgElement.append(document.createElementNS('http://www.w3.org/2000/svg', 'title'));

                if (svgElement.length) {
                  svgElementConfig.svgElement = svgElement[0];

                  if (!alreadyBound){
                    $(svgElement).on('click', this.instance.onEntityClick.bind({ instance: this.instance, entityId: entityId }));
                    alreadyBound = true;
                  }`

https://github.com/pkozul/ha-floorplan/blob/8a7405a1fb9afaf5eb9f1643aed8cead05ba689c/www/custom_ui/floorplan/ha-floorplan.html#L335

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
