### ISSUE TITLE
can't open in homeassistant ios app

### ISSUE THREAD

**Issue by zhujisheng** [pkozul/ha-floorplan#44]
can't open in homeassistant ios app
and can't open in safari

**Comment by darthsebulba04** [comment]
I second this.  I'm getting a spinning circle of death trying to load in app or safari on Mac, iPhone, and iPad.  Not seeing anything in the browser error logs to suggest an issue.

Running ha-floorplan 1.0.7.4 and hass 0.59.2 .

Is there a debug version that can be used to trace the where the issue might be?

Thanks.

**Comment by killadm** [comment]
can't open in firefox too

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
