### ISSUE TITLE
custom state card do't working in ha 0.59.1

### ISSUE THREAD

**Issue by kouweizhong** [pkozul/ha-floorplan#45]
![image](https://user-images.githubusercontent.com/5246029/33646651-a90ebd54-da8b-11e7-8b4d-8717905f41fd.png)

**Comment by ptorrezao** [comment]
Yep, same here.
No changes were made aside the upgrade and the card stopped working
BTW: panel_custom is OK.

**Comment by kouweizhong** [comment]
updated to 0.59.2, still can't work.

**Comment by ptorrezao** [comment]
@kouweizhong the changes on the configuration.yaml for the item frontend worked for me (is now working).
```
frontend:
javascript_version: latest
```

Sorry for the trouble @pkozul, i didn't saw the breaking changes. 
I think this one can be canceled, maybe a change on the installation tutorial would be nice but its not a bug. It's a feature :)

Note to future me: Read the God Damn release notes!

**Comment by kouweizhong** [comment]
@ptorrezao Oh, we must look at the release notes ah. TKS!
