### ISSUE TITLE
A bug in click 'Floorplan custom state card' item in 'Floorplan custom panel'

### ISSUE THREAD

**Issue by kouweizhong** [pkozul/ha-floorplan#46]
I created three Floorplan custom state cards and a Floorplan custom panel
![image](https://user-images.githubusercontent.com/5246029/33919839-beb2b57e-dff5-11e7-8623-b05dbdf4a86f.png)
![image](https://user-images.githubusercontent.com/5246029/33919902-188b9b6a-dff6-11e7-970c-e337237c1638.png)
  
I introduced the Floorplan custom state card virtual binary sensor on the Floorplan custom panel
![image](https://user-images.githubusercontent.com/5246029/33919963-5a5e6a72-dff6-11e7-9c0d-08b73966c4b1.png)
  
When I first click on 'binary_sensor.central_stations', the sensor information pops up correctly, but when I click on the other 'binary_sensor. *', It just pops up the message 'binary_sensor.central_stations'

![11 0](https://user-images.githubusercontent.com/5246029/33920363-88f7a590-dff8-11e7-85c0-a197522d52f9.gif)

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
