### ISSUE TITLE
Floorplan can be displayed on IOS, iPad, and safari, but it can't work

### ISSUE THREAD

**Issue by ekcuican** [pkozul/ha-floorplan#49]
HA 0.59.2
Floorplan can be displayed on IOS, iPad, and safari, but it can't work 。No control after clicking light or tv switch
What is the reason, please

**Comment by cyn42** [comment]
Just ran across this (HA 0.67.0 on iOS 11). I got it to work by disabling Pan/ Zoom.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
