### ISSUE TITLE
can't work with a zigbee switch without zero line,

### ISSUE THREAD

**Issue by axlzys** [pkozul/ha-floorplan#50]
thank you for you ha-floorplan. but i have a problem here.
i have a switch without N,only L, it is control by an gateway using zigbee.
but the switch without N will work sleep work sleep and go on,so it has high timeouts，it's a technical problem,and can't be solved.
in the floorplan when i touch the icon only one time.the switch will turn on,turn off,many times,i don't know why.because it's high timeouts?
in HA and homekit it work good,because i will not click the switch very quick。
I have try a switch with N,and control by same gateway using zigbee. it's work very good.
can you help me to fix it? sorry for my trouble English.

**Comment by axlzys** [comment]
and if i delete "action:toggle" in floorplan.yaml use turn_on/turn_off service,It's work good.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
