### ISSUE TITLE
Card View works on browser but not on Android

### ISSUE THREAD

**Issue by jimdineen** [pkozul/ha-floorplan#51]
I have a set up that works perfectly in Chrome browser (Windows) in both the panel and card view. Note: I had to put the dummy binary sensor in a group to get it to show up as per other threads on here,

However, on my android phone (in both chrome and firefox), whilst the panel floorplan works fine, the card view just displays the group name (Downstairs) and when you click on it you get a toggle switch to turn the group on which does nothing.

I have noted an error "Unable to find service binary_sensor/turn_on" but can't figure out how to resolve it and suspect that is the cause.

Any ideas about the above or where else to start looking?

Desktop Chrome:
![capture](https://user-images.githubusercontent.com/23137864/35012571-19269e7c-fb02-11e7-93ab-d5c251af86d9.PNG)

Android Chrome:
![ink 1](https://user-images.githubusercontent.com/23137864/35012627-51877822-fb02-11e7-948d-4a85450b23fd.png)

And when clicked:
![ink 2](https://user-images.githubusercontent.com/23137864/35012742-b60d6806-fb02-11e7-9e42-d61828cc67f8.png)

**Comment by jwmaas** [comment]
Did you resolve this issue? I have similar issue, only showing the dummy sensor, not the floorplan, with similar config text. Any ideas on how to resolve? Would be much appreciated!

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
