### ISSUE TITLE
Must specify at least one entity, even when an explodable group is also specified

### ISSUE THREAD

**Issue by natabat** [pkozul/ha-floorplan#54]
I'd like to create a Floorplan group that reuses a HA group, like so:
```
- name: Lights
  groups:
    - group.lights
...
```

However, I get the following error unless I also specify an entity. An empty 'entities' element does not do the trick.

> A group must contain either 'entities' or 'elements' in floorplan configuration

**Comment by herwinvw** [comment]
Fix:
change
let entityGroups = this.instance.config.groups.filter(x => x.entities
to
let entityGroups = this.instance.config.groups.filter(x => x.entities || x.groups);

and 
invalidGroups = this.config.groups.filter(x => !x.entities && !x.elements
...
to 
invalidGroups = this.config.groups.filter(x => !x.entities && !x.elements && !x.groups);
      if (invalidGroups.length) {
        this.isLoading = false;
        this.warn(`A group must contain either 'entities' or 'elements' or 'groups' in floorplan configuration`);
        return;
      }

In ha-floorplan.html as a workaround to fix this.

**Comment by LordMike** [comment]
I found the same thing, the code also showed me that `.groups` wasn't considered as an entities thingy.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
