### ISSUE TITLE
duplicate floorplans

### ISSUE THREAD

**Issue by jaburges** [pkozul/ha-floorplan#55]
not sure how much detail is needed but main floorplan community thread has most of it.
Seems related to state-card more than panel?
3.6.3  
0.63 HA

let me know if you need any extra info

**Comment by christopherbruce** [comment]
+1

**Comment by colindunn** [comment]
Was able to solve this for myself by adding this line to the beginning of `onAttached()` in `ha-floorplan.html`

```
if(Polymer.dom(this.$.floorplan).node.children.length > 0) return;
```

**Comment by lotohov** [comment]
i have duplicated floorplan in state card too , and i was asking for hel on hass forums [here details](https://community.home-assistant.io/t/strange-issue-with-floorplan-after-moving-to-hass-io/41123) but i am not familiar with javascript .. can you post full code line here.

**Comment by drmauro82** [comment]
@colindunn sorry I've added this line too but with no luck. the code is this, could you check please?

`onAttached() {
      if(Polymer.dom(this.$.floorplan).node.children.length > 0) return;
      window.onerror = this.handleWindowError.bind(this);

      if (!this.config.groups) {
        this.isLoading = false;
        this.warn(`Cannot find 'groups' in floorplan configuration`);
        return;
      }`

**Comment by carlberg** [comment]
Had the same issue and spent hours trying assorted fixes. Had this whle adding multiple floorplans and eventually I had to revert to just one floorplan and finally clearing the browser cache fixed it for me.

**Comment by mrfoxbit** [comment]
> Was able to solve this for myself by adding this line to the beginning of onAttached() in ha-floorplan.html
if(Polymer.dom(this.$.floorplan).node.children.length > 0) return;

@colindunn Thank you. 
It worked for me

**Comment by code-to-joy** [comment]
I'm seeing this as well. The workaround with adding the code row to onAttached() works to remedy this issue.

**Comment by colindunn** [comment]
Sorry have been away.

So this is what I did:
```
    onAttached: function() {
      if(Polymer.dom(this.$.floorplan).node.children.length > 0) return;
      window.onerror = this.handleWindowError.bind(this);

      if (!this.config.groups) {
        this.isLoading = false;
        this.warn(`Cannot find 'groups' in floorplan configuration`);
        return;
      }
```

It works for my situation, but I can't promise it will work for all. It's just a quick hack that works in my setup

**Comment by drmauro82** [comment]
remember to clear browser cache!

**Comment by jaburges** [comment]
seems this is closed
