### ISSUE TITLE
stopPropagation does not work on 0.65

### ISSUE THREAD

**Issue by colindunn** [pkozul/ha-floorplan#58]
After upgrading to 0.65, stopPropagation stopped working when using the state card and clicking on anything on the state card opens the more-info dialog instead of performing the action. Once the more-info dialog is open you then need to click on the entitiy within the svg.

I found the following changes worked for me to change it back to the way it usually works:

```diff
diff --git a/www/custom_ui/floorplan/ha-floorplan.html b/www/custom_ui/floorplan/ha-floorplan.html
index 8646f91..ff24732 100644
--- a/www/custom_ui/floorplan/ha-floorplan.html
+++ b/www/custom_ui/floorplan/ha-floorplan.html
@@ -59,7 +59,7 @@
       <ul></ul>
     </div>

-    <div id="floorplan" on-tap="stopPropagation"></div>
+    <div id="floorplan"></div>

   </template>

@@ -781,6 +781,7 @@
       else {
         this.instance.fire('hass-more-info', { entityId: entityId });
       }
+      e.stopPropagation();
     },

     getFill(stateConfig) {
```

Happy to create a PR, but they don't seem to be getting merged and I'll just conflict with the other PRs

**Comment by colindunn** [comment]
Actually, that didn't cover everything.

Instead I've just added:

```html
<div id="floorplan" on-click="stopPropagation"></div>
```

instead of

```html
<div id="floorplan" on-tap="stopPropagation"></div>
```

**Comment by colindunn** [comment]
Actually, after playing around with this a fair bit, I ended up just doing this:

```html
<div id="floorplan" on-tap="stopPropagation" on-click="stopPropagation"></div>
```

So my two primary devices are Chrome on OSX and Safari on iPhone. With both `on-tap` and `on-click` it seems to be working OK for me.

**Comment by aav7fl** [comment]
@pkozul Would you be able to add the `on-click="stopPropagation"` into the master branch div? This fixes the issue on clicking the statecard and having it popup for me as well.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
