### ISSUE TITLE
state-card-floorplan does not show, only sensor

### ISSUE THREAD

**Issue by jwmaas** [pkozul/ha-floorplan#60]
I think others have experienced same issue, but their solutions do not work for me. My custom floorplan works brilliantly as a side menu item. I even got my tv remote scripts to work without issues.

However, as a state-card it only shows the dummy floorplan mqtt sensor. When I click the sensor I get to see the floorplan on my mac, including a series of config items from the floorplan.yaml file (see enclosed 2nd picture). When I click on the sensor on my iPhone I get the floorplan, without error messages. I used the standard setup, including all the suggested yaml files and the other files in the right location. Is there anyone who experienced the same issue and who has resolved it?
Of course I'd like to show the floorplan immediately, without clicking the dummy sensor. Any suggestions are very much appreciated!! @pkozul , do you perhaps have suggestion?

![screen shot 2018-03-30 at 15 11 07](https://user-images.githubusercontent.com/16177874/38139392-829bd492-342f-11e8-8057-31cf0e2874d7.png)
![screen shot 2018-03-30 at 15 11 17](https://user-images.githubusercontent.com/16177874/38139393-82bcfdac-342f-11e8-9949-4df9e1e53c73.png)

**Comment by ScottyDS** [comment]
Hi,
I am experiencing exactly the same issue. With a fresh install of the latest Hassio, and HA-Floorplan, everything works as expected. As soon as I mess with the groups.yaml, the issue occurs. I have been struggling with this for days now, but cant seem to find a resolution.

The side-menu item works perfectly on PC and Android. On Android however, I do get to see the floorplan when I click on the sensor button, the same as on a PC, both using Google Chrome browser.

SideNote: I did have to turn off the pan&zoom feature, or else Android caused the whole of Hassio to crash. (Mosquitto, Samba, SSH, everything)

But other than this small issue, it is HA-Floorplan, TasmoAdmin and esphomeyaml is what swung me away from openHAB. A big thanks to all you folks that have crafted the solution. 

Update: Issue solved with the help of this video https://www.youtube.com/watch?v=EsBtyF5tZQ4 at the about 15:40 mark
Thanks BRuH.
Edited my groups.yaml with the following: 
Apologies for the graphic. I could not get the code block to work.

![image](https://user-images.githubusercontent.com/19373898/41786619-4e23bb2c-7646-11e8-91c1-b77b7ccc9c69.png)


![image](https://user-images.githubusercontent.com/19373898/41786827-d3682296-7646-11e8-83e1-2ec5bd2713dd.png)

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
