### ISSUE TITLE
state-card-floorplan shows floorplan multiple times

### ISSUE THREAD

**Issue by terrycarlin** [pkozul/ha-floorplan#61]
Every time I leave the states page to go to another page such as the developer console, when I go back to states page, there is another floorplan added to the card. I have seen three or more floorplans in the card. All of the floorpans work just fine. Using the latest code from this site with no changes except the normal configuration items.
I am using latest Safari.

**Comment by DennisSc** [comment]
here too - with chrome as well

**Comment by klejejs** [comment]
I have the same problem, would love to know the fix.

**Comment by RVC69** [comment]
Same problem with HA 0.69.1 and chrome 
![image](https://user-images.githubusercontent.com/36585182/40586560-ef769d24-61c3-11e8-8f50-34e791c43061.png)

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
