### ISSUE TITLE
Error after Update

### ISSUE THREAD

**Issue by MosquitoD4K** [pkozul/ha-floorplan#66]
Hi,

I get the following error, after updating to 70.1 and the newest version of floorplan. 

This only happens on my fire tablet and iPhone, but not in chrome on the desktop:

https://xxx/frontend_es5/custom-elements-es5-adapter.js:4:618 Uncaught TypeError: Class constructor HaFloorplan cannot be invoked without 'new'

**Comment by Spyyena** [comment]
I am having the same issue.

**Comment by Spyyena** [comment]
After doing some research, it seems this is because the browsers we are using are not "Up to date." https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs
https://github.com/whatwg/html/issues/1704#issuecomment-241816468

https://esdiscuss.org/topic/extending-an-es6-class-using-es5-syntax

**Comment by Spyyena** [comment]
I found the Solution. 
In HA .58, They updated the Javascript version, and kept backward compatibility. 
https://www.home-assistant.io/blog/2017/11/18/release-58/

It seems to be based off of the userAgent. For a day or two I was spoofing the userAgent, but this workaround seems to work permanently. 

The solution is to navigate to 
https://[YOURHASS].duckdns.org:8123/floorplan?latest

Note the "?latest" at the end.

or add the following to your configuration.yaml
```
frontend:
  javascript_version: latest
```

**Comment by stealthcopter** [comment]
@aspyhackr thanks, that fixed it for me! :+1:

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
