### ISSUE TITLE
Refresh Camera image 

### ISSUE THREAD

**Issue by jlbphotos** [pkozul/ha-floorplan#71]
Hi

Just adding this request as we discussed in PM @pkozul 

Would be great with the camera images feed in the rect refresh every few seconds just like the camera feed does in HA frontend. 
At the moment the camera feed only gets refreshed when you reload the page and sometimes its hours or days in the past.

thanks

**Comment by Spyyena** [comment]
You're pulling the wrong type of camera image. Try an mjpg feed instead of just an image

```
                {
                        module: "iFrame",
                        position: "bottom_left",
                        header: "Front Porch Camera",
                        config: {
                                url: "http://192.168.1.2:81/mjpg/Porch/video.mjpg?h=150&w=250&q=90",
                                height: "250px",
                                width: "350px"
                        }
                },
```
This is what my iFrame looks like accessing my BlueIris NVR in my config.js


If you have passwords bypassed on your local network, This should work too

`https://[YOUR HASS].duckdns.org:8123/api/camera_proxy_stream/camera.front_porch`

Additionally you can add `?api_password=YOUR_PASSWORD` to login any url Automatically.

**Comment by jlbphotos** [comment]
Sorry but im not sure what you mean, my camera in HA frontend feed works as it should and refreshes, but if i add to floorplan it doesnt refresh at all unless i refresh the page.

I have seen in the forum people with the same issue.

Im using foscam cameras and the foscam component

**Comment by Spyyena** [comment]
What does your config look like for floorplan?

**Comment by jlbphotos** [comment]
Here is my config

```
#camera#
  - name: Camera Images
    entities:
      - camera.foscam_camera
    camera_image_template: '${entity.attributes.entity_picture}'
```

To clarify I'm adding live feeds directly to my Floorplan not a button to open a pop-up. See here https://community.home-assistant.io/t/video-on-floorplan/27743/2

**Comment by Spyyena** [comment]
This issue appears to be on an problem located on the other branch. However, In reviewing it, Have you tried setting the CSS as referenced here?
https://community.home-assistant.io/t/video-on-floorplan/27743/21

On top of that, the black screen problem sounds similar to another issue I had. 
https://github.com/pkozul/ha-floorplan/issues/66#issuecomment-396081259

I am unable to change branches to experiment before I have to go to work today, but maybe its related to the Javascript version issue?

**Comment by jlbphotos** [comment]
My mistake, I thought I had posted this on that fork of Floorplan.

Actually seems like that fork is broken after the updates to 0.70 of HA, I had to replace the ha-floorplan.html from the main fork to fix, now the camera feed is not working at all anyway.

I'll have a look at the Css, thanks for the link.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
