### ISSUE TITLE
panel custom

### ISSUE THREAD

**Issue by rpeders** [pkozul/ha-floorplan#72]
I get a card saying that the panel_custom component could not  be set up. 
Anyone know how to fix this?

my panel_custom.yaml:
```
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
```

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
