### ISSUE TITLE
floorplan as custom cards for lovelace

### ISSUE THREAD

**Issue by luci-11** [pkozul/ha-floorplan#73]
Hello,
will you make floorplan compatible with new lovelace UI?

**Comment by estevez-dev** [comment]
I'm very interested in it too. It looks pretty simple according to docs: https://developers.home-assistant.io/docs/en/lovelace_custom_card.html but I'm new in shadow dom's and ES6 so for me it is hard to implement for now =(

**Comment by Briochorama** [comment]
I tried ... and failed miserably ... the thing is I'm just a enthusiast, nothing more. anyone could point me out to some resources that I could use to solve the issue ?

**Comment by MarcWim** [comment]
It feels like it should be easily possible. Will continue digging.

**Comment by pkozul** [comment]
See https://github.com/pkozul/lovelace-floorplan
