### ISSUE TITLE
SVG weather icon shows below the floorplan

### ISSUE THREAD

**Issue by dashony** [pkozul/ha-floorplan#77]
Hi Pkozul, I have found an issue where the weather icon loads according to the code based on the sensor.darksky_icon but the image displays way below the whole floorplan rather than in the rect I’ve created for it. I can confirm my code behind the svg has “viewBox” and not “viewbox” , and “0 0 64 64” as suggested in other posts but still showing the icon in the wrong place. Seems to be aligned vertically but not horizontally. 
The svg icons come from ammap.com as suggested yourself. Thanks

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
