### ISSUE TITLE
Help during set up...

### ISSUE THREAD

**Issue by ashdwells** [pkozul/ha-floorplan#83]
Hi 

I have followed instructions and can't get past this error:

Unable to set up dependencies of binary_sensor.mqtt. Setup failed for dependencies: mqtt

I'm stuck, any advice? 

Cheers

Ash

**Comment by rmarskell** [comment]
You need to have an mqtt broker / integration set up for this to work. You can use the mosquitto add-on and then set up the MQTT integration. See here: https://www.home-assistant.io/docs/mqtt/broker

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
