### ISSUE TITLE
Cannot change 2 objects in SVG

### ISSUE THREAD

**Issue by KuiBar** [pkozul/ha-floorplan#85]
Hi,

I am quite new to this and searche whole google but I can't find it. I can already style my Light Bulb so that it will be yellow when it is on en black when it is off.

I also like to give the room where the light bulb is in a gradient overlay. I have to objects in my svg:

light.gang_boven (Light bulb itself)
gangboven (The layer from that room)

Can someone help me?

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
