### ISSUE TITLE
what about the LICENSE of this repo?

### ISSUE THREAD

**Issue by butterl** [pkozul/ha-floorplan#89]
RT

**Comment by KyleMaas** [comment]
I was wondering about this in #80 as well.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan

**Comment by KyleMaas** [comment]
Glad to see some motion on it again!  This really was a handy feature.

**Comment by pkozul** [comment]
@KyleMaas 

Yep, we now have a small team working on it, so much more support is now available.
