### ISSUE TITLE
js error

### ISSUE THREAD

**Issue by b-shaw** [pkozul/ha-floorplan#90]
Trying to get floorplan working for the first time,  and all I get is a blank screen.  When I check errors in the dev console I see the following error:

ha-floorplan.html:183 TypeError: url.indexOf is not a function
    at Floorplan.cacheBuster (floorplan.js?_=1565876585119:1964)
    at Floorplan.fetchTextResource (floorplan.js?_=1565876585119:1855)
    at Floorplan.loadConfig (floorplan.js?_=1565876585119:139)
    at Floorplan.init (floorplan.js?_=1565876585119:65)
    at ha-floorplan.html:138
logError @ ha-floorplan.html:183
(anonymous) @ ha-floorplan.html:145
Promise.catch (async)
initFloorplan @ ha-floorplan.html:143
connectedCallback @ ha-floorplan.html:117
_attachDom @ app-652a7f4d.js:2
_readyClients @ app-652a7f4d.js:2
_flushClients @ app-652a7f4d.js:2
_propertiesChanged @ app-652a7f4d.js:2
_flushProperties @ app-652a7f4d.js:410
_flushProperties @ app-652a7f4d.js:2
ready @ app-652a7f4d.js:2
ready @ app-652a7f4d.js:2
ready @ app-652a7f4d.js:410
ready @ app-652a7f4d.js:410
ready @ app-652a7f4d.js:651
_enableProperties @ app-652a7f4d.js:410
connectedCallback @ app-652a7f4d.js:2
connectedCallback @ app-652a7f4d.js:2
connectedCallback @ app-652a7f4d.js:410
connectedCallback @ app-652a7f4d.js:410
(anonymous) @ 9ea472698d7ddb897773.chunk.js:1
Promise.then (async)
value @ 9ea472698d7ddb897773.chunk.js:1
value @ 9ea472698d7ddb897773.chunk.js:1
performUpdate @ app-652a7f4d.js:2
_enqueueUpdate @ app-652a7f4d.js:2
async function (async)
_enqueueUpdate @ app-652a7f4d.js:2
_requestUpdate @ app-652a7f4d.js:2
initialize @ app-652a7f4d.js:2
T @ app-652a7f4d.js:2
r @ 9ea472698d7ddb897773.chunk.js:1
value @ app-652a7f4d.js:876
_currentLoadProm.c.then._currentLoadProm @ app-652a7f4d.js:876
Promise.then (async)
value @ app-652a7f4d.js:876
performUpdate @ app-652a7f4d.js:2
_enqueueUpdate @ app-652a7f4d.js:2
async function (async)
_enqueueUpdate @ app-652a7f4d.js:2
_requestUpdate @ app-652a7f4d.js:2
set @ app-652a7f4d.js:2
value @ app-652a7f4d.js:876
async function (async)
value @ app-652a7f4d.js:876
value @ app-652a7f4d.js:1287
value @ app-652a7f4d.js:1287
performUpdate @ app-652a7f4d.js:2
_enqueueUpdate @ app-652a7f4d.js:2
async function (async)
_enqueueUpdate @ app-652a7f4d.js:2
_requestUpdate @ app-652a7f4d.js:2
initialize @ app-652a7f4d.js:2
T @ app-652a7f4d.js:2
n @ app-652a7f4d.js:876
n @ app-652a7f4d.js:1287
_clone @ app-652a7f4d.js:2
_commitTemplateResult @ app-652a7f4d.js:2
commit @ app-652a7f4d.js:2
a @ app-652a7f4d.js:2
U.render @ app-652a7f4d.js:2
update @ app-652a7f4d.js:2
performUpdate @ app-652a7f4d.js:2
_enqueueUpdate @ app-652a7f4d.js:2
async function (async)
_enqueueUpdate @ app-652a7f4d.js:2
_requestUpdate @ app-652a7f4d.js:2
initialize @ app-652a7f4d.js:2
initialize @ app-652a7f4d.js:2
T @ app-652a7f4d.js:2
U @ app-652a7f4d.js:2
i @ app-652a7f4d.js:1287
_clone @ app-652a7f4d.js:2
_commitTemplateResult @ app-652a7f4d.js:2
commit @ app-652a7f4d.js:2
update @ app-652a7f4d.js:2
_commitTemplateResult @ app-652a7f4d.js:2
commit @ app-652a7f4d.js:2
a @ app-652a7f4d.js:2
U.render @ app-652a7f4d.js:2
update @ app-652a7f4d.js:2
performUpdate @ app-652a7f4d.js:2
_enqueueUpdate @ app-652a7f4d.js:2
async function (async)
_enqueueUpdate @ app-652a7f4d.js:2
_requestUpdate @ app-652a7f4d.js:2
set @ app-652a7f4d.js:2
value @ app-652a7f4d.js:1362
t._updateHass @ hooks.js:391
(anonymous) @ app-652a7f4d.js:1362
n @ core-9f50dfce.js:1
(anonymous) @ core-9f50dfce.js:1
Promise.then (async)
c @ core-9f50dfce.js:1
subscribe @ core-9f50dfce.js:1
T @ core-9f50dfce.js:1
(anonymous) @ core-9f50dfce.js:1
Promise.then (async)
157 @ core-9f50dfce.js:1
o @ core-9f50dfce.js:1
(anonymous) @ core-9f50dfce.js:1
(anonymous) @ core-9f50dfce.js:1
2ha-floorplan.html:183 TypeError: url.indexOf is not a function
    at Floorplan.cacheBuster (floorplan.js?_=1565876585119:1964)
    at Floorplan.fetchTextResource (floorplan.js?_=1565876585119:1855)
    at Floorplan.loadConfig (floorplan.js?_=1565876585119:139)
    at Floorplan.init (floorplan.js?_=1565876585119:65)
    at ha-floorplan.html:138
logError @ ha-floorplan.html:183
(anonymous) @ ha-floorplan.html:145
Promise.catch (async)
initFloorplan @ ha-floorplan.html:143
connectedCallback @ ha-floorplan.html:117
_attachDom @ app-652a7f4d.js:2
_readyClients @ app-652a7f4d.js:2
_flushClients @ app-652a7f4d.js:2
_propertiesChanged @ app-652a7f4d.js:2
_flushProperties @ app-652a7f4d.js:410
_flushProperties @ app-652a7f4d.js:2
ready @ app-652a7f4d.js:2
ready @ app-652a7f4d.js:2
ready @ app-652a7f4d.js:410
ready @ app-652a7f4d.js:410
ready @ app-652a7f4d.js:651
_enableProperties @ app-652a7f4d.js:410
connectedCallback @ app-652a7f4d.js:2
connectedCallback @ app-652a7f4d.js:2
connectedCallback @ app-652a7f4d.js:410
connectedCallback @ app-652a7f4d.js:410
(anonymous) @ 9ea472698d7ddb897773.chunk.js:1
Promise.then (async)
value @ 9ea472698d7ddb897773.chunk.js:1
value @ 9ea472698d7ddb897773.chunk.js:1
performUpdate @ app-652a7f4d.js:2
_enqueueUpdate @ app-652a7f4d.js:2
async function (async)
_enqueueUpdate @ app-652a7f4d.js:2
_requestUpdate @ app-652a7f4d.js:2
initialize @ app-652a7f4d.js:2
T @ app-652a7f4d.js:2
r @ 9ea472698d7ddb897773.chunk.js:1
value @ app-652a7f4d.js:876
_currentLoadProm.c.then._currentLoadProm @ app-652a7f4d.js:876
Promise.then (async)
value @ app-652a7f4d.js:876
performUpdate @ app-652a7f4d.js:2
_enqueueUpdate @ app-652a7f4d.js:2
async function (async)
_enqueueUpdate @ app-652a7f4d.js:2
_requestUpdate @ app-652a7f4d.js:2
set @ app-652a7f4d.js:2
commit @ app-652a7f4d.js:2
commit @ app-652a7f4d.js:2
update @ app-652a7f4d.js:2
_commitTemplateResult @ app-652a7f4d.js:2
commit @ app-652a7f4d.js:2
a @ app-652a7f4d.js:2
U.render @ app-652a7f4d.js:2
update @ app-652a7f4d.js:2
performUpdate @ app-652a7f4d.js:2
_enqueueUpdate @ app-652a7f4d.js:2
async function (async)
_enqueueUpdate @ app-652a7f4d.js:2
_requestUpdate @ app-652a7f4d.js:2
set @ app-652a7f4d.js:2
commit @ app-652a7f4d.js:2
commit @ app-652a7f4d.js:2
update @ app-652a7f4d.js:2
_commitTemplateResult @ app-652a7f4d.js:2
commit @ app-652a7f4d.js:2
update @ app-652a7f4d.js:2
_commitTemplateResult @ app-652a7f4d.js:2
commit @ app-652a7f4d.js:2
a @ app-652a7f4d.js:2
U.render @ app-652a7f4d.js:2
update @ app-652a7f4d.js:2
performUpdate @ app-652a7f4d.js:2
_enqueueUpdate @ app-652a7f4d.js:2
async function (async)
_enqueueUpdate @ app-652a7f4d.js:2
_requestUpdate @ app-652a7f4d.js:2
set @ app-652a7f4d.js:2
value @ app-652a7f4d.js:1362
handleEvent @ app-652a7f4d.js:2
_boundHandleEvent @ app-652a7f4d.js:2
C @ app-652a7f4d.js:2
S @ app-652a7f4d.js:2
w @ app-652a7f4d.js:2
(anonymous) @ app-652a7f4d.js:2
_propertiesChanged @ app-652a7f4d.js:2
_flushProperties @ app-652a7f4d.js:410
_flushProperties @ app-652a7f4d.js:2
_invalidateProperties @ app-652a7f4d.js:2
_setProperty @ app-652a7f4d.js:2
Object.defineProperty.set @ app-652a7f4d.js:410
_locationChanged @ app-652a7f4d.js:1123
D @ app-652a7f4d.js:2
w @ app-652a7f4d.js:2
v @ app-652a7f4d.js:2
_propertiesChanged @ app-652a7f4d.js:2
_flushProperties @ app-652a7f4d.js:410
_flushProperties @ app-652a7f4d.js:2
_invalidateProperties @ app-652a7f4d.js:2
_setProperty @ app-652a7f4d.js:2
Object.defineProperty.set @ app-652a7f4d.js:410
__computeRoutePath @ app-652a7f4d.js:1128
D @ app-652a7f4d.js:2
w @ app-652a7f4d.js:2
v @ app-652a7f4d.js:2
_propertiesChanged @ app-652a7f4d.js:2
_flushProperties @ app-652a7f4d.js:410
_flushProperties @ app-652a7f4d.js:2
_invalidateProperties @ app-652a7f4d.js:2
(anonymous) @ app-652a7f4d.js:2
_propertiesChanged @ app-652a7f4d.js:2
_flushProperties @ app-652a7f4d.js:410
_flushProperties @ app-652a7f4d.js:2
_invalidateProperties @ app-652a7f4d.js:2
_setProperty @ app-652a7f4d.js:2
Object.defineProperty.set @ app-652a7f4d.js:410
_urlChanged @ app-652a7f4d.js:1123
(anonymous) @ app-652a7f4d.js:2
fire @ app-652a7f4d.js:410
_globalOnClick @ app-652a7f4d.js:1123
(anonymous) @ app-652a7f4d.js:2
Show 46 more frames
6core-9f50dfce.js:1 WebSocket connection to 'ws://192.168.1.64:8123/api/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
e @ core-9f50dfce.js:1
(anonymous) @ core-9f50dfce.js:1
createSocket @ core-9f50dfce.js:1
(anonymous) @ core-9f50dfce.js:1
s @ core-9f50dfce.js:1
(anonymous) @ core-9f50dfce.js:1

**Comment by b-shaw** [comment]
Can this be related to #88?  I think I have all the latest versions. II've been going round& round with this for quite a while now getting nowhere.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
