### ISSUE TITLE
floorplan as a lovelace card

### ISSUE THREAD

**Issue by nick9one1** [pkozul/ha-floorplan#92]
The floor plans work great, but is it possible to use them as a lovelace card?

**Comment by starboywizzy521** [comment]
excuse me how you get it working ? 
this is my problem : https://github.com/pkozul/ha-floorplan/issues/93

please help me

**Comment by dreamweaver0314** [comment]
> The floor plans work great, but is it possible to use them as a lovelace card?
I found the way to use floorplan as a lovelace card. :)
For your reference: [check it out~](https://github.com/pkozul/ha-floorplan/issues/93#issuecomment-568827780)

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
