### ISSUE TITLE
floorplan state card doesn't display anything

### ISSUE THREAD

**Issue by starboywizzy521** [pkozul/ha-floorplan#93]
I followed all steps right but it doesn't work. I don't get any error but the floorplan doesn't display. I only get the sensor circle icon. This is my config screenshot

**configuration.yaml :**
![vs1](https://user-images.githubusercontent.com/40290563/71408657-4c1d3880-263f-11ea-8792-0ad6741ddc7d.png)
![vs2](https://user-images.githubusercontent.com/40290563/71408676-5808fa80-263f-11ea-9363-7e49c1f4165c.png)

**customize.yaml:**
![customize yaml  ](https://user-images.githubusercontent.com/40290563/71408727-7ec73100-263f-11ea-9456-59fed6ec0819.png)

**groups.yaml**
![groups yaml ](https://user-images.githubusercontent.com/40290563/71408755-943c5b00-263f-11ea-9053-6ef2e44faabc.png)

**my browser output**:
![bowser](https://user-images.githubusercontent.com/40290563/71408850-de254100-263f-11ea-9481-963bc34c37ca.png)

Please help me !

**Comment by dreamweaver0314** [comment]
I have the same problem too.
Currently I can show the floorplan with custom panel, but custom-state-card failed.
I'm not sure if it was caused by lovelace or something else.
Can somebody help us? Thanks! : )

**Comment by dreamweaver0314** [comment]
> I have the same problem too.
> Currently I can show the floorplan with custom panel, but custom-state-card failed.
> I'm not sure if it was caused by lovelace or something else.
> Can somebody help us? Thanks! : )

Hey guys,
I just found that if we want to use custom-state-card in Lovelace UI, we should use another git: [https://github.com/pkozul/lovelace-floorplan](https://github.com/pkozul/lovelace-floorplan)! 
It works now! :)

**Comment by bbrendon** [comment]
Is this what you're looking for ?
https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489?u=bbrendon

**Comment by dreamweaver0314** [comment]
> Is this what you're looking for ?
> https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489?u=bbrendon

Yes. Thank you very much~! : )
