### ISSUE TITLE
Integrating Floorplan to Tileboard

### ISSUE THREAD

**Issue by ned-kelly** [pkozul/ha-floorplan#96]
I'm wanting to integrate my floorplan into a custom Tileboard dashboard / page for my tablet.

Is it possible to somehow directly load the floor plan component in a URL without loading the rest of the Home Assistant UI? (For example) `/local/custom_ui/floorplan/ha-floorplan.html`  

As you can see in the current screenshot  - when the user goes to my 'floorplan' dashboard it's actually loading all of home assistant in the iframe - I'm looking for just the SVG with the elements ideally (and ability to customise background etc), and not the HA header, side nav etc...

![image](https://user-images.githubusercontent.com/17648709/77596257-3d4c6780-6f47-11ea-9495-30f07f83e5fa.png)

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
